Make examples under the documentation annotation more descriptive.
wso2-extensions/siddhi-io-email pull request #13
Opened 2017-10-31 13:18 UTC by ChathurikaA

## Purpose
> Improve the documentation of siddhi-io-email.

## Approach
> Add more examples under documentation annotation.

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

2017-10-31 16:55 UTC, tishan89 requested changes

2017-10-31 16:55 UTC, tishan89 commented on component/src/main/java/org/wso2/extension/siddhi/io/email/sink/EmailSink.java
> +                    throw new RuntimeException("Error is encountered while connecting to the smtp server" +
Add full-stop and a space to end of line

2017-10-31 16:55 UTC, tishan89 commented on component/src/main/java/org/wso2/extension/siddhi/io/email/sink/EmailSink.java
> +                        + " the smtp server" + e.getMessage(), e);
There is a repeating the and missing full-stop and space

2017-10-31 17:14 UTC, ChathurikaA commented on component/src/main/java/org/wso2/extension/siddhi/io/email/sink/EmailSink.java
> +                    throw new RuntimeException("Error is encountered while connecting to the smtp server" +
Fix in #8b4b372

2017-10-31 17:14 UTC, ChathurikaA commented on component/src/main/java/org/wso2/extension/siddhi/io/email/sink/EmailSink.java
> +                        + " the smtp server" + e.getMessage(), e);
Fix in #8b4b372

2017-11-01 14:28 UTC, tishan89 approved these changes

2017-11-01 15:22 UTC, merged