Adds ability to set and send custom headers
wso2-extensions/siddhi-io-email pull request #60
Opened 2019-10-25 17:23 UTC by tishan89

## Purpose
Adds support to send custom headers though email sink. Users can pass custom headers as parameters in sink configuration which will be populated in the out going email as headers.

## Approach
Introduced a convention to add custom headers to sink configurations so that we can handle them separately. Any parameter in sink configuration with name starting from 'header.' will be treated as a custom header. Which ever follows the 'header.' will be treated as the actual header name and parameter value would be header value

## Documentation
Added to the sink class

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

2019-10-25 20:18 UTC, suhothayan requested changes
We don’t follow this approach in other extensions. We use header = key,value kind of a format. Please refer HTTP io for reference

2019-10-28 09:46 UTC, tishan89 commented
@suhothayan That approach hasn't addressed the issue of header key/value containing ':' . According to the spec header key can contain any ascii character. In the method used in this code we don't use split hence it is handled.

2019-10-28 10:31 UTC, tishan89 commented
@suhothayan Fixed as discssed

2019-10-28 10:36 UTC, suhothayan approved these changes

2019-10-28 10:36 UTC, merged